"""Three-perspective synthesis for ADW planning phase.

Implements the core SYNTHAI concept in ~50 lines instead of 7,900.
Each perspective is generated by a different provider, then synthesized.
"""

import asyncio
from typing import Tuple

from adw_modules.providers import call_llm
from adw_modules.data_types import SynthesisResult


# Perspective prompts - hardcoded, not configurable
PERSPECTIVES = {
    "technical": """Analyze this GitHub issue from a TECHNICAL ARCHITECTURE perspective.

Focus on:
- System design implications
- Data flow and dependencies
- API changes required
- Performance considerations
- Technical debt impact

Issue:
{issue}

Provide a structured technical analysis in 300-500 words.""",

    "user": """Analyze this GitHub issue from a USER EXPERIENCE perspective.

Focus on:
- User workflow impact
- UI/UX changes needed
- Accessibility considerations
- Error handling and feedback
- Documentation needs

Issue:
{issue}

Provide a structured UX analysis in 300-500 words.""",

    "risk": """Analyze this GitHub issue from a RISK AND FAILURE MODES perspective.

Focus on:
- What could go wrong
- Edge cases to handle
- Security implications
- Rollback considerations
- Testing requirements

Issue:
{issue}

Provide a structured risk analysis in 300-500 words.""",
}


SYNTHESIS_PROMPT = """You are synthesizing three expert perspectives into a unified implementation plan.

TECHNICAL PERSPECTIVE (from Claude):
{technical}

USER EXPERIENCE PERSPECTIVE (from GPT-4):
{user}

RISK PERSPECTIVE (from Gemini):
{risk}

Create a comprehensive implementation plan that:
1. Addresses all technical requirements from the technical analysis
2. Optimizes for user experience based on the UX analysis
3. Mitigates risks identified in the risk analysis
4. Provides clear, actionable steps

Output a structured plan with:
- Summary (2-3 sentences)
- Implementation steps (numbered)
- Testing requirements
- Success criteria

Be specific and actionable. This plan will guide AI implementation."""


async def get_perspectives(issue: str) -> Tuple[str, str, str]:
    """Get three perspectives concurrently from different providers.
    
    Args:
        issue: The GitHub issue content (title + body)
        
    Returns:
        Tuple of (technical, user, risk) perspectives
    """
    technical, user, risk = await asyncio.gather(
        call_llm("anthropic", PERSPECTIVES["technical"].format(issue=issue)),
        call_llm("openai", PERSPECTIVES["user"].format(issue=issue)),
        call_llm("gemini", PERSPECTIVES["risk"].format(issue=issue)),
    )
    return technical, user, risk


async def synthesize_perspectives(issue: str) -> SynthesisResult:
    """Generate three perspectives and synthesize into a unified plan.
    
    This is what SYNTHAI was supposed to be: ~100 lines, not 7,900.
    
    Args:
        issue: The GitHub issue content (title + body)
        
    Returns:
        SynthesisResult with all perspectives and synthesized plan
    """
    print("🔍 Generating three perspectives...")
    
    # Get perspectives concurrently
    technical, user, risk = await get_perspectives(issue)
    
    print("✅ Perspectives complete. Synthesizing...")
    
    # Synthesize using Anthropic (best for structured output)
    synthesized = await call_llm(
        "anthropic",
        SYNTHESIS_PROMPT.format(technical=technical, user=user, risk=risk)
    )
    
    print("✅ Synthesis complete.")
    
    return SynthesisResult(
        technical_perspective=technical,
        user_perspective=user,
        risk_perspective=risk,
        synthesized_plan=synthesized,
        providers_used=["anthropic", "openai", "gemini"],
    )


async def synthesize_issue(issue_title: str, issue_body: str) -> str:
    """Convenience function for synthesizing a GitHub issue.
    
    Args:
        issue_title: GitHub issue title
        issue_body: GitHub issue body
        
    Returns:
        Synthesized implementation plan as string
    """
    issue_content = f"# {issue_title}\n\n{issue_body}"
    result = await synthesize_perspectives(issue_content)
    return result.synthesized_plan
