"use client";

import { motion } from "framer-motion";

const features = [
  {
    emoji: "🎨",
    title: "One-Click Magic",
    description:
      "No coding, no CSS editing. Just browse, click, and watch your ChatGPT transform instantly.",
  },
  {
    emoji: "🔒",
    title: "Privacy First",
    description:
      "We never read or store your conversations. Your chats stay completely private.",
  },
  {
    emoji: "✨",
    title: "Designer Quality",
    description:
      "Each theme is crafted by real designers—not generated by AI. Quality you can feel.",
  },
];

export function FeaturesSection() {
  return (
    <section id="features" className="py-24 px-8 lg:px-16 bg-cream">
      {/* Section Header */}
      <div className="text-center mb-16">
        <p
          className="text-[0.8rem] font-semibold uppercase tracking-[0.2em] mb-3"
          style={{ color: "#5BB5A2" }}
        >
          Why ThemeGPT
        </p>
        <h2
          className="text-[clamp(2rem,4vw,3rem)] font-semibold tracking-tight"
          style={{ fontFamily: "var(--font-fraunces), serif" }}
        >
          Simple. Beautiful. Yours.
        </h2>
      </div>

      {/* Feature Cards */}
      <div className="flex flex-col md:flex-row justify-center gap-8 flex-wrap max-w-[1100px] mx-auto">
        {features.map((feature, index) => (
          <motion.div
            key={feature.title}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.4, delay: index * 0.15 }}
            className="bg-white p-8 rounded-[24px] w-full md:w-[320px] transition-all duration-400 hover:-translate-y-2"
            style={{
              boxShadow: "0 8px 32px rgba(74, 55, 40, 0.06)",
              border: "1px solid rgba(74, 55, 40, 0.05)",
            }}
          >
            <span className="text-[2.5rem] block mb-4">{feature.emoji}</span>
            <h3
              className="text-[1.25rem] font-semibold mb-2"
              style={{ fontFamily: "var(--font-fraunces), serif" }}
            >
              {feature.title}
            </h3>
            <p
              className="text-[0.95rem] leading-relaxed"
              style={{ color: "#7A6555" }}
            >
              {feature.description}
            </p>
          </motion.div>
        ))}
      </div>
    </section>
  );
}
